language: scala

scala:
  - 2.11.12
  - 2.12.4

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: G5Pnx6Lwd7V3xYBB/MnZloXXuuBG8wsGGAWIJhJ1og/cuRGFdc+rr8TLvQtXx/EJ/zCuol//03eEg76cE7rF1CPb7rGMRpi+QkqoYKL7+b3fz3rr5L3SDRCFMwyH2ArsNsastsX4rmrsrrF3wACklYdHkreK40CMTUUZ/hDlpkS4Snv4t8wM1VcNm1VxL32E32T+iIFkzhq4u7nqHzm4o5jc43P/R3YGIAdmDdr1azMvXV/dKrGt7PBQmFeJMv8EU1/Oe4xjoJgcS9temeZA/YFkPfpzPMrBJomlLM5CJdj3R9oI3lPJaVZ1WsFqjQU7tcMfHQUy2XZhhbS8krXA4HtM/XP1oWTd2FYqBGGisz68z/JttWvpu1xwXFIytpAtS6NSB1Q6LQvvsduJgqVX5rhyFqpIvF9gAuanTRB6rFrC8zvq+DhH4yAdw610PZsJcpRtBvOnPNE4uZKky0iXmNnZNgowDW7gy8OnW5pQ8+kTsZcXEFF/bjLBZLjjJx+1ziigs9R3WMekqwjb2uXMPpU5R3KMntt8ODZKp0uq5oh22qVcefXon8o0bAN2GBZDsQvrBByiIBwTClaUNnCtyZLppaw+1julyjx/Z+H8vlguJ/Y+wBXvIjEeUGv9rJ3JpYSW/xAY2fUu90aV53pMKPruybc9KtL9SKVjt2D2yfo=
  - secure: l5ThATo6P/1at/fttRo+9+RdJHQcrVmb5X/dlzhBrTY9Mv3wl1ZYDKYMVIkc/Ac9FBnrUAGRRSlhff2auZTlmEocuTbMAtbRzmZ4k6dEvgfGvMu76mYLg+N0j4ML2bFdMyg5e1IaJl/de9YLtu3P336nVw1ex2Zhl5IR6lhAxpCsmLIEEeFOqn63Xq2Hg1wD0BQsfLQ5CSs2zyzN0TqpCXwxp70CzBzIIwj93qbaCUKgmcRANDI1q7R0wWkUXJIrTHpdc5Q29ecf3Cm4VHHSxk5xSLJ9lPp2HSn/YcF4RXc2t5bieKipMib2qTJXj2eS8lS9W8vDfC9WcrR7S6Cd8FSgM6Sj0jTyCTIoaXaXtOSTT0ldUugtmjsLcPHiW7RS4JcJYjVg036+W3aV7M+xv2DSap+9P4ZT3oVIpFj5z9fQiAlNxYOb0FqvY+c89P6WTioeRvdgYHseXPlAjfYVICBPQPiHFHrKbTDWagNwAib9jBvKGOXiKaS29EC77flJqebmDUjHVsKtVDdJMV7earFD8ea+Oohv1pUWKAim5aBvFJewRFd9ceBsw0y9gyjqQ2xzC9xgBRbQ/tay5bYqEqy0frLt7oQXSDjCbyVd59ikVSMGu/ubGxyCxRhi23oa057dRlc2RgnRZrCLB/qIa6NcFrX8EHBKUk6Jw9zTFxE=
  - secure: mCgNgV7Odv0vI7LTNjSN3Tuvae/NX3DGWc+03vI55Op6sYuqZRaS4RAg8oVYWlRosuXmQuauZ5F4ua4KyrelxSehnCKaSeCicA+llq7/C2p0Fbh+oloZM6/AB5VN2wpUg6/W0MunQyRyGRchrzkQwKCuxScgoBF8x0uVVKJ+rSda8mtDf8uewktHwxB18TPLPIapuHFd1InAF2jDEidQ1oIuHAnRCrfZMD25DL41PXEphC4DUHQjX9dJ6rXZO9sy8kJ/+v+ycb605gQvpQwkPzFFcj1K/+xlku68u/nQBaBf3kd8SSlMM2/0KRjDBDdpzEhXntW0AVReqJtx7oYMlAygerNyGpDcAS9BICQHNukrfNR5bOrFntIvljetaLN4vubECE7sa3ypZiynoyV9zRcwqMZnPuRO+7oqOFEFgrpFXSJJPpev83kBsCAcdvnPhJKKU3wzVbhi1lL6Klwc+XMksSoXkxbQJXpg23JRjR+y5t804sdr4zwahJ4xdz/75YXAGYCorSB4tydSPC8gvHNk84wpCoJnG0m1mLgTXoLSz/sZhT/N2jfGlyTnO8HPhhn1tmYA+x8b4XYOwy4qlo+ENgJKeAFJUdvQp0716cJbYUxfg9TLjjSbj/8Ow9CMGnG+UUeyw4TJGEaMw2XpCLCwpB0E/L9h5VdCqw22EGc=
  - secure: guIrAoBMKABQVhTH8bK8pJQRDI8+b946KsjU/3fpCE2mMQ9hOBDiJnTciecqm3CjkQuQwRlrmHAqdWUdFs0/gYJEeuXRCoLRPUECBm9I8KC2ENsPzy3F3WgkiUjtU1PFkX+/siiqdL171Vi372VpLcZ0nIWDSTZ/CTbhvg9bFuIQPAy9meNvN0PvC5LuOsqLJ+Zx+GKVTaaXk0kEtGivqeFNVI4Dle1N1xUsKPK1kLZsLmd0D8S/emfcRjxTINkwSII5H0gG+h4GwlBE4AhWsCkvn6RyOUvKlBJomiFjxea6CpChqsCD54bZ7Zwsu/TWdkCpOaGNQiastFn/qwCsYjCbL/TtMouVqdEUmWkviXAYE0iQvEtzXMyx1fV2QhCgMEuc/UKsCt3XxGgp1IAjwDGPLxM844wT/GKIQUMZ1H2TalZ7RHqQysdRyKpCa4txsEvsWfhAEBQaYtq34Q3wWFJV/LKEsAwa70ikan/Ap1TTcMGYTtsq5Sc692XeozWUli78Y+bbVxnfbgBuXmC4GBaoXC/nSuUiuqxADPdywpWZtof8UZfwzeYdb48PmY58Joyl+W8WYYWjZ+KcsHeUNsMrJq8J9AysniEZ1KE8Y44hRuVO2epGz3s4NcNqZCB6Fa+3NyGAKJFmHbY8/2RJEVUjycRh0TCwyJL8wdqHH50=
